version: 2.1
jobs:
  compile:
   docker:
      - image: bryanhafidz/bryan-docker:0x02
   steps:
      - run:
          command: |
           git config --global user.name "RysepProject"
           git config --global user.email "RysepProjects@gmail.com"
           git clone https://github.com/RysepProject/kernel_xiaomi_onclite -b JandaX JandaX
           cd Xerl
           chmod a+x gettools.sh
           ./gettools.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
